version: '3.8'
services:
  postgres:
    image: postgres
    restart: always
    container_name: postgres-documentnow
    ports:
      - 4001:5432
    environment:
      - DATABASE_HOST=127.0.0.1
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=documentnow

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: 'admin@admin.com'
      PGADMIN_DEFAULT_PASSWORD: 'admin'
    ports:
      - 8080:80
    depends_on:
      - postgres
